apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hybg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hybg
    app.kubernetes.io/part-of: ci10t-786-0056-app
  name: devfile-sample-hybg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hybg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hybg
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0056-tenant/ci10t-786-0056-app/devfile-sample-hybg@sha256:b4c099e58d8504d14eecb86328a52275de73f6607ede7b0323026e52bfac221e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
